import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "../globals.css";

const sarabunFont = Sarabun ({
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  display: "swap"
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  // title: "Create Next App",
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
    >
      <body className={sarabunFont.className}>
        <h1 className="text-4xl">สวัสดี วัฒนา</h1>
          <hr />
          {children}
      </body>
    </html>
  );
}
