import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "../globals.css";

export const promptFont = Prompt({
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  display: "swap"
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
    >
      <body className={promptFont.className}>
        <h1 className="text-4xl">สวัสดี header 2</h1>
        <hr />
        {children}
      </body>
    </html>
  );
}
