// http://localhost:3000/course
// เอา (front) layout.tsx มาเป็น url

import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar";

export const promptFont = Prompt({
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th">
      <body className="{promptFont.className}">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
